version: '3.7'

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    restart: always
    ports:
      - '80:3000'
    command: 'npm run start'
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
